INSERT INTO cars_catalog (
    id,
    make,
    model,
    cylinders,
    drive,
    fuel1,
    fuel2,
    engine_descriptor,
    luggage_volume,
    passenger_volume,
    transmission,
    size_class,
    model_year,
    electric_motor,
    base_model
) VALUES
      (1, 'Nissan', 'Rogue AWD', 3, 'All-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic (AV-S8)', 'Small Sport Utility Vehicle 4WD', 2023, NULL, 'Rogue'),
      (2, 'Ford', 'Explorer RWD', 6, 'Rear-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S10)', 'Standard Sport Utility Vehicle 2WD', 2023, NULL, 'Explorer'),
      (3, 'Ford', 'Expedition 4WD', 6, 'Part-time 4-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S10)', 'Standard Sport Utility Vehicle 4WD', 2023, NULL, 'Expedition'),
      (4, 'Oldsmobile', 'Ninety-Eight/Touring', 6, 'Front-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic 4-spd', 'Large Cars', 1988, NULL, 'Ninety-Eight/Touring'),
      (5, 'BMW', 'M4 Competition Coupe', 6, 'Rear-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S8)', 'Subcompact Cars', 2024, NULL, 'M'),
      (6, 'BMW', '430i xDrive Gran Coupe', 4, 'All-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S8)', 'Compact Cars', 2024, NULL, '4 Series'),
      (7, 'Buick', 'Encore GX FWD', 3, 'Front-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic (variable gear ratios)', 'Small Sport Utility Vehicle 2WD', 2024, NULL, 'Encore'),
      (8, 'Buick', 'Encore GX AWD', 3, 'All-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic 9-spd', 'Small Sport Utility Vehicle 4WD', 2024, NULL, 'Encore'),
      (9, 'MINI', 'Cooper S Countryman', 4, 'Front-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic (AM-S7)', 'Midsize Cars', 2024, NULL, 'Countryman'),
      (10, 'Acura', 'Integra', 4, 'Front-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic (AV-S7)', 'Large Cars', 2024, NULL, 'Integra'),
      (11, 'Alfa Romeo', 'Stelvio', 4, 'Rear-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic 8-spd', 'Small Sport Utility Vehicle 2WD', 2024, NULL, 'Stelvio'),
      (12, 'Acura', 'MDX AWD', 6, 'All-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S10)', 'Small Sport Utility Vehicle 4WD', 2024, NULL, 'MDX'),
      (13, 'Acura', 'MDX AWD Type-S', 6, 'All-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S10)', 'Standard Sport Utility Vehicle 4WD', 2024, NULL, 'MDX'),
      (14, 'Audi', 'e-tron S Sportback (21/22 inch wheels)', NULL, 'All-Wheel Drive', 'Electricity', NULL, NULL, NULL, NULL, 'Automatic (A1)', 'Standard Sport Utility Vehicle 4WD', 2023, 138.0, 'e-tron S'),
      (15, 'Kia', 'Telluride AWD', 6, 'All-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S8)', 'Small Sport Utility Vehicle 4WD', 2024, NULL, 'Telluride'),
      (16, 'Buick', 'Enclave FWD', 6, 'Front-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic 9-spd', 'Standard Sport Utility Vehicle 2WD', 2024, NULL, 'Enclave'),
      (17, 'Chevrolet', 'Corvette Z06 Carbon Aero', 8, 'Rear-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S8)', 'Two Seaters', 2024, NULL, 'Corvette'),
      (18, 'Alfa Romeo', 'Giulia', 6, 'Rear-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic 8-spd', 'Midsize Cars', 2024, NULL, 'Giulia'),
      (19, 'Mitsubishi', 'Space Wagon', 4, 'Front-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic 3-spd', 'Small Station Wagons', 1988, NULL, 'Space Wagon'),
      (20, 'Land Rover', 'Discovery', 4, '4-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S8)', 'Standard Sport Utility Vehicle 4WD', 2024, NULL, 'Discovery'),
      (21, 'Mercedes-Benz', 'GLS580 4matic', 8, 'All-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic 9-spd', 'Standard Sport Utility Vehicle 4WD', 2024, 48.0, 'GLS-Class'),
      (22, 'Polestar', '2 Dual Motor (19 Inch Wheels)', NULL, 'All-Wheel Drive', 'Electricity', NULL, NULL, NULL, NULL, 'Automatic (A1)', 'Midsize Cars', 2024, 200.0, '2'),
      (23, 'Volvo', 'C40 Recharge twin', NULL, 'All-Wheel Drive', 'Electricity', NULL, NULL, NULL, NULL, 'Automatic (A1)', 'Small Sport Utility Vehicle 4WD', 2024, 135.0, 'C40'),
      (24, 'Rivian', 'R1S 20 inch All-Terrain Dual Large', NULL, 'Part-time 4-Wheel Drive', 'Electricity', NULL, NULL, NULL, NULL, 'Automatic (A1)', 'Standard Sport Utility Vehicle 4WD', 2023, 208.0, 'R1S'),
      (25, 'Audi', 'S4', 6, 'All-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S8)', 'Compact Cars', 2024, NULL, 'S4'),
      (26, 'Toyota', 'Corolla Wagon', 4, 'Front-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S10)', 'Small Sport Utility Vehicle 2WD', 2024, NULL, 'Corolla'),
      (27, 'Toyota', 'Camry XLE/XSE', 4, 'Front-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S8)', 'Midsize Cars', 2024, NULL, 'Camry'),
      (28, 'Honda', 'Pilot FWD', 6, 'Front-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S10)', 'Small Sport Utility Vehicle 2WD', 2024, NULL, 'Pilot'),
      (29, 'Kia', 'Sorento Hybrid FWD', 4, 'Front-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic (AM-S6)', 'Small Sport Utility Vehicle 2WD', 2024, 270.0, 'Sorento'),
      (30, 'Audi', 'Q5 S line quattro', 4, 'All-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic (AM-S7)', 'Small Sport Utility Vehicle 4WD', 2024, NULL, 'Q5');