INSERT INTO cars_catalog (
    make,
    model,
    cylinders,
    drive,
    fuel1,
    fuel2,
    engine_descriptor,
    luggage_volume,
    passenger_volume,
    transmission,
    size_class,
    model_year,
    electric_motor,
    base_model
) VALUES
      ('Nissan', 'Rogue AWD', 3, 'All-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic (AV-S8)', 'Small Sport Utility Vehicle 4WD', 2023, NULL, 'Rogue'),
      ('Ford', 'Explorer RWD', 6, 'Rear-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S10)', 'Standard Sport Utility Vehicle 2WD', 2023, NULL, 'Explorer'),
      ('Ford', 'Expedition 4WD', 6, 'Part-time 4-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S10)', 'Standard Sport Utility Vehicle 4WD', 2023, NULL, 'Expedition'),
      ('Oldsmobile', 'Ninety-Eight/Touring', 6, 'Front-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic 4-spd', 'Large Cars', 1988, NULL, 'Ninety-Eight/Touring'),
      ('BMW', 'M4 Competition Coupe', 6, 'Rear-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S8)', 'Subcompact Cars', 2024, NULL, 'M'),
      ('BMW', '430i xDrive Gran Coupe', 4, 'All-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S8)', 'Compact Cars', 2024, NULL, '4 Series'),
      ('Buick', 'Encore GX FWD', 3, 'Front-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic (variable gear ratios)', 'Small Sport Utility Vehicle 2WD', 2024, NULL, 'Encore'),
      ('Buick', 'Encore GX AWD', 3, 'All-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic 9-spd', 'Small Sport Utility Vehicle 4WD', 2024, NULL, 'Encore'),
      ('MINI', 'Cooper S Countryman', 4, 'Front-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic (AM-S7)', 'Midsize Cars', 2024, NULL, 'Countryman'),
      ('Acura', 'Integra', 4, 'Front-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic (AV-S7)', 'Large Cars', 2024, NULL, 'Integra'),
      ('Alfa Romeo', 'Stelvio', 4, 'Rear-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic 8-spd', 'Small Sport Utility Vehicle 2WD', 2024, NULL, 'Stelvio'),
      ('Acura', 'MDX AWD', 6, 'All-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S10)', 'Small Sport Utility Vehicle 4WD', 2024, NULL, 'MDX'),
      ('Acura', 'MDX AWD Type-S', 6, 'All-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S10)', 'Standard Sport Utility Vehicle 4WD', 2024, NULL, 'MDX'),
      ('Audi', 'e-tron S Sportback (21/22 inch wheels)', NULL, 'All-Wheel Drive', 'Electricity', NULL, NULL, NULL, NULL, 'Automatic (A1)', 'Standard Sport Utility Vehicle 4WD', 2023, 138.0, 'e-tron S'),
      ('Kia', 'Telluride AWD', 6, 'All-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S8)', 'Small Sport Utility Vehicle 4WD', 2024, NULL, 'Telluride'),
      ('Buick', 'Enclave FWD', 6, 'Front-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic 9-spd', 'Standard Sport Utility Vehicle 2WD', 2024, NULL, 'Enclave'),
      ('Chevrolet', 'Corvette Z06 Carbon Aero', 8, 'Rear-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S8)', 'Two Seaters', 2024, NULL, 'Corvette'),
      ('Alfa Romeo', 'Giulia', 6, 'Rear-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic 8-spd', 'Midsize Cars', 2024, NULL, 'Giulia'),
      ('Mitsubishi', 'Space Wagon', 4, 'Front-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic 3-spd', 'Small Station Wagons', 1988, NULL, 'Space Wagon'),
      ('Land Rover', 'Discovery', 4, '4-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S8)', 'Standard Sport Utility Vehicle 4WD', 2024, NULL, 'Discovery'),
      ('Mercedes-Benz', 'GLS580 4matic', 8, 'All-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic 9-spd', 'Standard Sport Utility Vehicle 4WD', 2024, 48.0, 'GLS-Class'),
      ('Polestar', '2 Dual Motor (19 Inch Wheels)', NULL, 'All-Wheel Drive', 'Electricity', NULL, NULL, NULL, NULL, 'Automatic (A1)', 'Midsize Cars', 2024, 200.0, '2'),
      ('Volvo', 'C40 Recharge twin', NULL, 'All-Wheel Drive', 'Electricity', NULL, NULL, NULL, NULL, 'Automatic (A1)', 'Small Sport Utility Vehicle 4WD', 2024, 135.0, 'C40'),
      ('Rivian', 'R1S 20 inch All-Terrain Dual Large', NULL, 'Part-time 4-Wheel Drive', 'Electricity', NULL, NULL, NULL, NULL, 'Automatic (A1)', 'Standard Sport Utility Vehicle 4WD', 2023, 208.0, 'R1S'),
      ('Audi', 'S4', 6, 'All-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S8)', 'Compact Cars', 2024, NULL, 'S4'),
      ('Toyota', 'Corolla Wagon', 4, 'Front-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S10)', 'Small Sport Utility Vehicle 2WD', 2024, NULL, 'Corolla'),
      ('Toyota', 'Camry XLE/XSE', 4, 'Front-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S8)', 'Midsize Cars', 2024, NULL, 'Camry'),
      ('Honda', 'Pilot FWD', 6, 'Front-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic (S10)', 'Small Sport Utility Vehicle 2WD', 2024, NULL, 'Pilot'),
      ('Kia', 'Sorento Hybrid FWD', 4, 'Front-Wheel Drive', 'Regular Gasoline', NULL, NULL, NULL, NULL, 'Automatic (AM-S6)', 'Small Sport Utility Vehicle 2WD', 2024, 270.0, 'Sorento'),
      ('Audi', 'Q5 S line quattro', 4, 'All-Wheel Drive', 'Premium Gasoline', NULL, NULL, NULL, NULL, 'Automatic (AM-S7)', 'Small Sport Utility Vehicle 4WD', 2024, NULL, 'Q5');